config/routes.rb
Rails.application.routes.draw do
  devise_for :planners, controllers: {
    sessions:      'planners/sessions',
    passwords:     'planners/passwords',
    registrations: 'planners/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root "projects#index"

  resources :projects do
    collection do
      get  'list'
      post 'purchase'
    end
  end

  resources :projects, only: [:show,] do
    resources :investments, only: [:show] do
      resources :supporters, only: [:new, :create] do
        collection do
          post 'confirm'
        end
      end
    end
  end
  resources :planners, only: [:index] do
    resources :projects, only: [:new, :create]
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'password'
    end
  end

  resources :planners, only: [:index, :show, :edit, :update] do
    member do
      get 'password'
      get 'introduction'
    end
  end
end

app/models/planner.rb
class Planner < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
### Association
  has_many :investments
  has_many :projects
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

end

app/controllers/planners/confirmations_controller.rb
class Planners::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/planners/omniauth_callbacks_controller.rb
class Planners::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/planners/passwords_controller.rb
class Planners::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/planners/registrations_controller.rb
class Planners::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
   def update
      self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
      prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
      if resource.update_without_current_password(account_update_params)
        yield resource if block_given?
        if is_flashing_format?
          flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
            :update_needs_confirmation : :updated
          set_flash_message :notice, flash_key
        end
        sign_in resource_name, resource, :bypass => true
        respond_with resource, :location => after_update_path_for(resource)
      else
        clean_up_passwords resource
        respond_with resource
      end
    end


  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/planners/sessions_controller.rb
class Planners::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    if (session[:previous_url] == root_path)
      super
    else
      session[:previous_url] || root_path
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/planners/unlocks_controller.rb
class Planners::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/planners_controller.rb
class PlannersController < ApplicationController
  before_action :set_planner, only: [:update, :edit, :password]

  def introduction
    @planner = Project.find(params[:id]).planner
    @project = @planner.projects.order(created_at: :DESC).limit(1)
  end

  def show
  end

  def edit
  end

  def password
  end

  def update
    if @planner.update(planner_params)
      sign_in(@planner, bypass: true)
      redirect_to root_path, notice:"企画者プロフィールが編集されました。"
    else
      flash.now[:alert] = "プロフィール編集が失敗しました。"
      render :edit
    end
  end

  private
  def planner_params
    params.require(:planner).permit(:name, :image, :email, :location, :birthday, :password, :password_confirmation, :introduction)
  end

  def set_planner
    @planner = Planner.find(params[:id])
    @hold_planner = Planner.find(params[:id])
  end
end

app/helpers/planners_helper.rb
module PlannersHelper
end

app/views/planners/edit.html.haml
= render partial: "projects/header"
.mypage__edit
  .edit__left
    .mypage__left__box
      - if current_planner.image.present?
        = image_tag("#{@planner.image}", class: "mypage__image", size: "175x175")
      - else
        = image_tag("icon_yellow.png", class: "mypage__image", size: "175x175")
    .mypage__edit__name #{@hold_planner.name}
    .mypage__main__left
      .mypage__border
      .mypage__menu__title
        = image_tag("black-people.png", class: "mypage__menu__title-image")
        .mypage__menu__title-text サポーター
      .mypage__inbox
        .mypage__menu
          = link_to "支援したプロジェクト", "", class: "mypage__menu__body"
          = link_to ">", "", class: "mypage__menu__icon"
      .mypage__inbox
        .mypage__menu
          = link_to "購入履歴(ストア)", "", class: "mypage__menu__body"
          = link_to ">", "", class: "mypage__menu__icon"
      .mypage__inbox.inbox__last
        .mypage__menu
          = link_to "メッセージ", "", class: "mypage__menu__body"
          = link_to ">", "", class: "mypage__menu__icon"
      .mypage__border
      .mypage__menu__title
        = image_tag("men.gif", class: "mypage__menu__title-image")
        .mypage__menu__title-text アカウント情報
      .mypage__inbox
        .mypage__menu
          = link_to "プロフィール編集", edit_planner_path, class: "mypage__menu__body"
          = link_to ">", edit_planner_path, class: "mypage__menu__icon"
      .mypage__inbox.inbox__last
        .mypage__menu
          = link_to "メール通知設定", "", class: "mypage__menu__body"
          = link_to ">", "", class: "mypage__menu__icon"
      .mypage__menu__title
        .mypage__menu__title-text{style: "margin: 13px 0 0 12px;"} セキュリティについて
      .security__box
        .security__text 当サイトはSSL暗号化通信に対応しておりますので、入力した情報は安全に送信されます。
        = image_tag("siteSealImage.gif", class: "security__image")
  .edit__right
    .mypage__main__right
      .right__title
        %h2 企画者情報編集
      = form_for (@planner), url: planner_path do |f|
        .profile__field
          .profile__field__text 企画者名
          .profile__field__box
            = f.text_field :name, class: 'profile__field__box-form', placeholder: '例）若松大輔'
            - if @planner.errors.full_messages_for(:name).any?
              .profile__error 企画者名を入力してください。
        .profile__field
          .profile__field__text イメージ写真
          .profile__field__box
            = f.file_field :image, style: "margin-left:12px;"
        .profile__field
          .profile__field__text メールアドレス
          .profile__field__box
            = f.text_field :email, class: 'profile__field__box-form'
          - if @planner.errors.full_messages_for(:email).any?
            .post__error メールアドレスを入力してください。
        .profile__field
          .profile__field__text パスワード
          .profile__field__box
            = link_to "編集", password_planner_path, class: "profile__pass__edit"
        .profile__field
          .profile__field__text 現在地
          .profile__field__box
            = f.text_field :location, class: 'profile__field__box-form'
        .profile__field
          .profile__field__text 誕生日
          .profile__field__box
            = f.text_field :birthday, class: 'profile__field__box-form'
        .profile__field
          .profile__field__text 自己紹介
          .profile__field__box
            = f.text_area :introduction, class: 'profile__field__long'
        .profile__submit
          = f.submit "変更する", class: "profile__submit__btn"
= render partial: "projects/footer"

app/views/planners/introduction.haml
= render partial: "projects/header"
.intro
.intro__area
  .intro__box
    = image_tag("#{@planner.image}", class: "intro__box-image", size: "175x175")
    .intro__name #{@planner.name}
    .intro__profile
      .intro__date 現在地:#{@planner.location}
      .intro__date 誕生日:#{@planner.birthday.year}年#{@planner.birthday.month}月#{@planner.birthday.day}日
    .intro__detail #{@planner.introduction}
  .mypage__main
    .mypage__main__left
      .mypage__border
      .mypage__menu__title
        = image_tag("black-people.png", class: "mypage__menu__title-image")
        .mypage__menu__title-text サポーター
      .mypage__inbox
        .mypage__menu
          = link_to "支援したプロジェクト", "", class: "mypage__menu__body"
          = link_to ">", "", class: "mypage__menu__icon"
      .mypage__inbox.inbox__last
        .mypage__menu
          = link_to "お気に入りのプロジェクト", "", class: "mypage__menu__body"
          = link_to ">", "", class: "mypage__menu__icon"
      .mypage__border
      .mypage__menu__title
        = image_tag("men.gif", class: "mypage__menu__title-image")
        .mypage__menu__title-text 実行者
      .mypage__inbox.inbox__last
        .mypage__menu
          = link_to "投稿したプロジェクト", "", class: "mypage__menu__body"
          = link_to ">", "", class: "mypage__menu__icon"
    .mypage__main__right
      .right__title
        %h2 投稿したプロジェクト
        = link_to "投稿したプロジェクト一覧へ", "", class: "mypage__new__more"
      - @project.each do |project|
        .intro__project
          .intro__project__left
            = link_to "/projects/#{project.id}" do
              - if project.clear_rate.round(0) >= 100
                = image_tag("success.png", class: "intro__top__success")
              = image_tag("#{project.main_image}", class: "intro__top__image", size: "310x175")
          .intro__project__right
            = link_to "/projects/#{project.id}" do
              .intro__right__text #{project.main_title}
            .intro__planner
              = link_to introduction_planner_path(project.id), class: "intro__planner-link" do
                - if project.planner.image.present?
                  = image_tag("#{project.planner.image}", class: "intro__planner-link-image")
                - else
                  = image_tag("icon_yellow.png", class: "intro__planner-link-image")
              .intro__planner-box
                = link_to introduction_planner_path(project.id) do
                  .intro__planner-box-name #{project.planner.name}
                = link_to "", class: "intro__planner-genre" do
                  = image_tag("pencil.gif", class: "intro__planner-genre-image", size: "24x24")
                  .intro__planner-genre-name 料理 エンタメ
            .intro__money
              .intro__box__money
                = image_tag("yen.gif", class: "money__image", size: "21x21")
                .intro__money__title 集まっている金額
                .intro__money__sum #{project.sum_price.to_s(:delimited)}円
              .intro__box__gage
                .intro__money__gage
                  - if project.clear_rate.round(0) > 100
                    .intro__money__gage__in{style: "width:100%" }
                      .intro__money__gage__in__percent #{project.clear_rate.round(0)}%
                  - else
                    .intro__money__gage__in{style: "width:#{project.clear_rate.round(0)}%" }
                      .intro__money__gage__in__percent #{project.clear_rate.round(0)}%
              .intro__box__limit
                .intro__box__limit-in
                  = image_tag("people.gif", class: "intro__money__supporter-image", size: "20x20")
                  .intro__money__supporter-name サポーター
                .intro__money__supporter-count #{project.investments.map{|investment|(investment.supporters.count)}.sum}人
                .intro__limit-in
                  = image_tag("clock-small.gif", class: "intro__limit-image", size: "20x20")
                  .intro__limit-title 残り
                .intro__limit-days #{(project.end_date - Date.today).to_i}日
      .right__title
        %h2 支援したプロジェクト
        = link_to "支援したプロジェクト一覧へ", "", class: "mypage__new__more"
      .right__body 支援しているプロジェクトはありません。
      .right__title
        %h2 お気に入りのプロジェクト
        = link_to "お気に入りに追加したプロジェクト一覧へ", "", class: "mypage__new__more"
      .right__body お気に入りに追加しているプロジェクトはありません。
= render partial: "projects/footer"

app/views/planners/password.haml
= render partial: "projects/header"
.mypage__edit
  .edit__left
    .mypage__left__box
      - if current_planner.image.present?
        = image_tag("#{@planner.image}", class: "mypage__image", size: "175x175")
      - else
        = image_tag("icon_yellow.png", class: "mypage__image", size: "175x175")
    .mypage__edit__name #{@hold_planner.name}
    .mypage__main__left
      .mypage__border
      .mypage__menu__title
        = image_tag("black-people.png", class: "mypage__menu__title-image")
        .mypage__menu__title-text サポーター
      .mypage__inbox
        .mypage__menu
          = link_to "支援したプロジェクト", "", class: "mypage__menu__body"
          = link_to ">", "", class: "mypage__menu__icon"
      .mypage__inbox
        .mypage__menu
          = link_to "購入履歴(ストア)", "", class: "mypage__menu__body"
          = link_to ">", "", class: "mypage__menu__icon"
      .mypage__inbox.inbox__last
        .mypage__menu
          = link_to "メッセージ", "", class: "mypage__menu__body"
          = link_to ">", "", class: "mypage__menu__icon"
      .mypage__border
      .mypage__menu__title
        = image_tag("men.gif", class: "mypage__menu__title-image")
        .mypage__menu__title-text アカウント情報
      .mypage__inbox
        .mypage__menu
          = link_to "プロフィール編集", edit_planner_path, class: "mypage__menu__body"
          = link_to ">", edit_planner_path, class: "mypage__menu__icon"
      .mypage__inbox.inbox__last
        .mypage__menu
          = link_to "メール通知設定", "", class: "mypage__menu__body"
          = link_to ">", "", class: "mypage__menu__icon"
      .mypage__menu__title
        .mypage__menu__title-text{style: "margin: 13px 0 0 12px;"} セキュリティについて
      .security__box
        .security__text 当サイトはSSL暗号化通信に対応しておりますので、入力した情報は安全に送信されます。
        = image_tag("siteSealImage.gif", class: "security__image")
  .edit__right
    .mypage__main__right
      .right__title
        %h2 パスワード変更
      = form_for (@planner), url: planner_path do |f|
        .profile__field
          = f.label :password, "新しいパスワード", class: 'profile__field__text'
          - if @minimum_password_length
            %em
              (#{@minimum_password_length} characters minimum)
            %br/
          .profile__field__box
            = f.password_field :password, class: 'profile__field__box-form'
        .profile__field
          = f.label :password_confirmation, "パスワード(確認)", class: 'profile__field__text'
          .profile__field__box
            = f.password_field :password_confirmation, class: 'profile__field__box-form'
        .profile__submit
          = f.submit "変更する", class: "profile__submit__btn"
= render partial: "projects/footer"

app/views/planners/show.html.haml
= render partial: "projects/header"
.mypage__own
  .mypage__own__box
    .mypage__left__box
      - if current_planner.image.present?
        = image_tag("#{current_planner.image}", class: "mypage__image", size: "175x175")
      - else
        = image_tag("icon_yellow.png", class: "mypage__image", size: "175x175")
    .mypage__right__box
      .mypage__account-name #{current_planner.name}
      .mypage__news
        .mypage__news__days 2017/07/05
        = link_to "【実行者様向け】7/11（火）システムメンテナンスのお知らせ", "", class: "mypage__news__body"
      .mypage__news
        .mypage__news__days 2017/06/13
        = link_to "【新機能】お気に入り＃タグ機能 の提供が開始されました！", "", class: "mypage__news__body"
      .mypage__news
        .mypage__news__days 2017/05/23
        = link_to "【重要】Makuake利用規約 変更のお知らせ", "", class: "mypage__news__body"
      = link_to "お知らせ一覧を見る", "", class: "mypage__new__more"
.mypage__main
  .mypage__main__left
    .mypage__border
    .mypage__menu__title
      = image_tag("black-people.png", class: "mypage__menu__title-image")
      .mypage__menu__title-text サポーター
    .mypage__inbox
      .mypage__menu
        = link_to "支援したプロジェクト", "", class: "mypage__menu__body"
        = link_to ">", "", class: "mypage__menu__icon"
    .mypage__inbox
      .mypage__menu
        = link_to "購入履歴(ストア)", "", class: "mypage__menu__body"
        = link_to ">", "", class: "mypage__menu__icon"
    .mypage__inbox.inbox__last
      .mypage__menu
        = link_to "メッセージ", "", class: "mypage__menu__body"
        = link_to ">", "", class: "mypage__menu__icon"
    .mypage__border
    .mypage__menu__title
      = image_tag("men.gif", class: "mypage__menu__title-image")
      .mypage__menu__title-text アカウント情報
    .mypage__inbox
      .mypage__menu
        = link_to "プロフィール編集", edit_planner_path, class: "mypage__menu__body"
        = link_to ">", edit_planner_path, class: "mypage__menu__icon"
    .mypage__inbox.inbox__last
      .mypage__menu
        = link_to "メール通知設定", "", class: "mypage__menu__body"
        = link_to ">", "", class: "mypage__menu__icon"
    .mypage__menu__title
      .mypage__menu__title-text{style: "margin: 13px 0 0 12px;"} セキュリティについて
    .security__box
      .security__text 当サイトはSSL暗号化通信に対応しておりますので、入力した情報は安全に送信されます。
      = image_tag("siteSealImage.gif", class: "security__image")
  .mypage__main__right
    .right__title
      %h2 支援したプロジェクト
      = link_to "支援したプロジェクト一覧へ", "", class: "mypage__new__more"
    .right__body 支援しているプロジェクトはありません。
    .right__title
      %h2 購入履歴(ストア)
      = link_to "購入履歴(ストア)一覧へ", "", class: "mypage__new__more"
    .right__body 購入した商品はありません。
= render partial: "projects/footer"