config/routes.rb
Rails.application.routes.draw do
  devise_for :planners, controllers: {
    sessions:      'planners/sessions',
    passwords:     'planners/passwords',
    registrations: 'planners/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root "projects#index"

  resources :projects do
    collection do
      get  'list'
      post 'purchase'
    end
  end

  resources :projects, only: [:show,] do
    resources :investments, only: [:show] do
      resources :supporters, only: [:new, :create] do
        collection do
          post 'confirm'
        end
      end
    end
  end
  resources :planners, only: [:index] do
    resources :projects, only: [:new, :create]
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'password'
    end
  end

  resources :planners, only: [:index, :show, :edit, :update] do
    member do
      get 'password'
      get 'introduction'
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  mount_uploader :main_image, ImageUploader
  mount_uploader :intro_image, ImageUploader
  mount_uploader :desc_image, ImageUploader
  mount_uploader :content_image, ImageUploader
  mount_uploader :feature_image, ImageUploader

  has_many :users
  belongs_to :planner
  has_many :investments
  accepts_nested_attributes_for :investments
  has_many :introductions
  accepts_nested_attributes_for :introductions
  has_many :introduction_bodies
  accepts_nested_attributes_for :introduction_bodies
  has_many :introduction_images
  accepts_nested_attributes_for :introduction_images


  validates :main_title, presence: true,      length: { maximum: 50 }
  validates :goal_price, presence: true,      length: { maximum: 7 }
  validates :end_date, presence: true
  validates :main_image, presence: true

  acts_as_ordered_taggable_on :genre

  def clear_rate
    self.investments.map{|investment|(investment.supporters.count)*(investment.price)}.sum/(self.goal_price.to_i).to_f*100
  end

  def sum_price
    self.investments.map{|investment|(investment.supporters.count)*investment.price}.sum
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.order(created_at: :DESC).includes(:planner).limit(9)
    @new_projects = Project.order(created_at: :DESC).includes(:planner).limit(8)
  end

  def list
    @project = Project.all
  end

  def show
    @project = Project.includes(:investments).find(params[:id])
    @project_show = (Array(@project.introductions).push(Array(@project.introduction_bodies)).push(Array(@project.introduction_images))).flatten!
    @project_show.sort! do |a, b|
      a[:intro_index] <=> b[:intro_index]
    end
  end

  def new
    @project = Project.new
    @project.investments.build
    @project.introductions.build
    @project.introduction_bodies.build
    @project.introduction_images.build
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to root_path, notice: "企画が投稿されました。"
    else
      flash.now[:alert] = "未入力項目があります。"
      # render :new
      redirect_to new_planner_project_path, alert: "未入力項目があります。"
    end
  end

  private
  def project_params
    params.require(:project).permit(:main_title, :goal_price, :end_date, :main_image, genre_list:[], investments_attributes: [:title, :body, :price, :image, :stock, :delivery_date], introductions_attributes: [:intro_index, :title], introduction_bodies_attributes: [:intro_index, :body], introduction_images_attributes: [:intro_index, :image]).merge(planner_id: current_planner.id)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_footer.haml
.footer
  .footer__box
    .top
      .top__left
        .top__search
          .top__search__title プロジェクトを探す
          .top__search__border
          %ul.top__search__menu
            %li
              = link_to "プロダクト", "/", class: "top__search__menu-list"
            %li
              = link_to "ファッション", "/", class: "top__search__menu-list"
            %li
              = link_to "フード", "/", class: "top__search__menu-list"
            %li
              = link_to "レストラン・バー", "/", class: "top__search__menu-list"
            %li
              = link_to "テクノロジー", "/", class: "top__search__menu-list"
            %li
              = link_to "more >", "/", class: "top__search__menu-list more-edit"
        .top__publish
          .top__search__title プロジェクトを掲載する
          .top__search__border
          %ul.top__search__menu
            %li
              = link_to "プロジェクト How To", "/", class: "top__search__menu-list"
          = link_to "/" do
            = image_tag("sample22.jpg", class: "top__publish-image")
      .top__center
        .top__menu
          .top__search__title MENU
          .top__search__border
          = link_to "/" do
            = image_tag("footer_store.jpg", class: "top__menu-image")
          %ul.top__search__menu
            %li
              = link_to "ヘルプ", "/", class: "top__search__menu-list"
            %li
              = link_to "プレスリリース", "/", class: "top__search__menu-list"
            %li
              = link_to "お問い合わせ・取材受付", "/", class: "top__search__menu-list"
      .top__right
        .top__official
          .top__search__title オフィシャルアカウント 
          .top__search__border
          .top__official__makuake
            = image_tag("logo-big.png", style: "width:340px")
          .top__official__facebook
          = link_to "Makuake_caをフォロー", "/", class: "top__official__sns twitter"
          = link_to "line@", "/", class: "top__official__sns line"
          = link_to "Instagram", "/", class: "top__official__sns instagram"
    .bottom
      .bottom__text Copyright © CyberAgent Crowd Funding, Inc. All Rights Reserved.main__content__catch-copy.
      = link_to "プライバシーポリシー", "https://www.makuake.com", class: "bottom__text-link"
      = link_to "利用規約", "https://www.makuake.com", class: "bottom__text-link"
      = link_to "運営会社", "https://www.makuake.com", class: "bottom__text-link"

    %p{id: "page-top"}
      %a{href: "#wrap"}
        = image_tag("page_top.png")

app/views/projects/_header.haml
.header
  .inbox
    = link_to "/" do
      = image_tag("makuake-logo.png", class: "inbox__logo")
    .search__form
      = form_tag('/', method: :get) do
        %input.search__form__box{name: "title"}
        %label
          %input{type: "submit", value: "探す", class: "search__form__btn"}
          %i.search__form__btn-image{class: "fa fa-search faa-ring animated"}
    - if user_signed_in? && planner_signed_in?
      .inbox__icon
        = link_to "プロジェクトを掲載する", new_planner_project_path(current_planner), class: "inbox__icon-published"
        = link_to "/" do
          %i.inbox__icon-heart{class: "fa fa-heart-o faa-pulse animated"}
        = link_to "/" do
          %i.inbox__icon-mail{class: "fa fa-envelope-o faa-shake animated"}
        = link_to "/" do
          %i.inbox__icon-bell{class: "fa fa-bell-o faa-ring animated"}
        .inbox__icon__imagebox
          = image_tag("icon_yellow.png", class: "inbox__icon__imagebox-own header__right__btn",size: "35x35") 
          .more.more__position
            %ul.more__list.header__right__menu
              %li
                = link_to 'ユーザーマイページ', user_path(current_user), class: "more__list__text", method: :get
              %li
                = link_to '企画者マイページ', planner_path(current_planner), class: "more__list__text", method: :get
              %li
                = link_to 'ログアウト', destroy_user_session_path, class: "more__list__text", method: :delete

    - elsif !user_signed_in? && !planner_signed_in?
      .inbox__icon
        %a.inbox__icon-published{data: {toggle: "modal", target: "#my-modal-login-planner"}} プロジェクトを掲載する
        %i.inbox__icon-small-heart{class: "fa fa-heart-o faa-pulse animated"}
        = link_to "お気に入り", "", class: "inbox__icon-favorite"
        .signup__btn.icon-right.header__left__btn
          新規登録
          .more
            %ul.more__list.header__left__menu
              %li
                %a.more__list__text{data: {toggle: "modal", target: "#my-modal-signup"}} ユーザー登録
              %li
                %a.more__list__text{data: {toggle: "modal", target: "#my-modal-signup-planner"}} 企画者登録
        .signin__btn.icon-right.header__right__btn
          ログイン
          .more
            %ul.more__list.header__right__menu
              %li
                %a.more__list__text{data: {toggle: "modal", target: "#my-modal-login"}} ユーザーログイン
              %li
                %a.more__list__text{data: {toggle: "modal", target: "#my-modal-login-planner"}} 企画者ログイン

    - elsif user_signed_in?
      .inbox__icon
        %a.inbox__icon-published{data: {toggle: "modal", target: "#my-modal-login-planner"}} プロジェクトを掲載する
        %i.inbox__icon-small-heart{class: "fa fa-heart-o faa-pulse animated"}
        = link_to "お気に入り", "", class: "inbox__icon-favorite"
        .inbox__icon__imagebox.icon-right.mypage__top-position
          - if current_user.image.present?
            = image_tag("#{current_user.image}", class: "inbox__icon__imagebox-own header__right__btn",size: "35x35")
          - else
            = image_tag("icon_yellow.png", class: "inbox__icon__imagebox-own header__right__btn",size: "35x35") 
          .more.more__position
            %ul.more__list.header__right__menu
              %li
                = link_to 'ユーザーマイページ',  user_path(current_user), class: "more__list__text", method: :get
              %li
                = link_to 'ログアウト', destroy_user_session_path, class: "more__list__text", method: :delete
        .signin__btn.icon-right.planner__margin.header__left__btn
          企画者
          .more
            %ul.more__list.header__left__menu
              %li
                %a.more__list__text{data: {toggle: "modal", target: "#my-modal-signup-planner"}} 企画者登録
              %li
                %a.more__list__text{data: {toggle: "modal", target: "#my-modal-login-planner"}} 企画者ログイン

    - else planner_signed_in?
      .inbox__icon
        = link_to "プロジェクトを掲載する", new_planner_project_path(current_planner), class: "inbox__icon-published"
        %i.inbox__icon-small-heart{class: "fa fa-heart-o faa-pulse animated"}
        = link_to "お気に入り", "", class: "inbox__icon-favorite"
        .inbox__icon__imagebox.icon-right.mypage__top-position
          = image_tag("icon_yellow.png", class: "inbox__icon__imagebox-own header__right__btn",size: "35x35") 
          .more.more__position
            %ul.more__list.header__right__menu
              %li
                = link_to '企画者マイページ', planner_path(current_planner), class: "more__list__text", method: :get
              %li
                = link_to 'ログアウト', destroy_planner_session_path, class: "more__list__text", method: :delete
        .signin__btn.icon-right.planner__margin.header__left__btn
          ユーザー
          .more
            %ul.more__list.header__left__menu
              %li
                %a.more__list__text{data: {toggle: "modal", target: "#my-modal-signup"}} ユーザー登録
              %li
                %a.more__list__text{data: {toggle: "modal", target: "#my-modal-login"}} ユーザーログイン

.modal#my-modal-login
  .modal-dialog
    .login.my-modal-view
      %h2.login__title ユーザーログイン
      %a.login__link{data: {toggle: "modal", target: "#my-modal-signup", dismiss:"modal"}} 新規会員登録はこちら  >
      = render partial: "devise/shared/login_new"

.modal#my-modal-signup
  .modal-dialog
    .login.my-modal-view
      %h2.login__title ユーザー登録
      %a.login__link{data: {toggle: "modal", target: "#my-modal-login", dismiss:"modal"}} ログインはこちら >
      %p.login__copy ＼約1分で登録でき、Makuakeを楽しめます!／
      = render partial: "devise/shared/signup_new"

.modal#my-modal-login-planner
  .modal-dialog
    .login.my-modal-view
      %h2.login__title 企画者ログイン
      %a.login__link{data: {toggle: "modal", target: "#my-modal-signup-planner", dismiss:"modal"}} 新規企画者登録はこちら  >
      %p.login__copy ＼企画を投稿するには、企画者情報の登録が必要です!／
      = render partial: "planners/shared/login_new"

.modal#my-modal-signup-planner
  .modal-dialog
    .login.my-modal-view
      %h2.login__title 企画者登録
      %a.login__link{data: {toggle: "modal", target: "#my-modal-login-planner", dismiss:"modal"}} 企画者ログインはこちら >
      %p.login__copy ＼企画を投稿するには、企画者情報の登録が必要です!／
      = render partial: "planners/shared/signup_new"

app/views/projects/_index_recommend.haml
/ おすすめプロジェクト一覧
.recommend
  - @projects.each do |project|
    .recommend__area
      = link_to "/projects/#{project.id}", class: "recommend__top" do
        - if project.clear_rate.round(0) >= 100
          = image_tag("success.png", class: "recommend__top-success")
        = image_tag("#{project.main_image}", class: "recommend__top-image", size: "310x170")
        - if (project.created_at.since(3.days)) >= Date.today
          .recommend__top__new New!
        %h2.recommend__top-text #{project.main_title}
      .recommend__planner
        = link_to introduction_planner_path(project.id), class: "recommend__planner-link" do
          - if project.planner.image == nil
            = image_tag("icon_yellow.png", class: "recommend__planner-link-image", size: "36x36")
          - else
            = image_tag("#{project.planner.image}", class: "recommend__planner-link-image", size: "36x36")
          .recommend__planner-link-name #{project.planner.name}
        = link_to "", class: "recommend__planner-genre" do
          = image_tag("pencil.gif", class: "recommend__planner-genre-image", size: "24x24")
          .recommend__planner-genre-name 料理 エンタメ
      .recommend__money
        .box__money
          %dl
            %dt.money
              = image_tag("yen.gif", class: "money__image", size: "25x25")
              .money__title 集まっている金額
            %dd.money__sum #{project.sum_price.to_s(:delimited)}円
        .box__gage
          .money__gage
            - if project.clear_rate.round(0) > 100
              .money__gage__in{style: "width:100%" }
                .money__gage__in__percent #{project.clear_rate.round(0)}%
            - else
              .money__gage__in{style: "width:#{project.clear_rate.round(0)}%" }
                .money__gage__in__percent #{project.clear_rate.round(0)}%
        .box__limit
          .box__limit-in
            %dl
              %dt.money__supporter
                = image_tag("people.gif", class: "money__supporter-image", size: "24x24")
                .money__supporter-name サポーター
              %dd.money__supporter-count #{project.investments.map{|investment|(investment.supporters.count)}.sum}人
          .box__limit-in
            %dl
              %dt.money__limit
                = image_tag("clock-small.gif", class: "money__limit-image", size: "24x24")
                .money__limit-title 残り
                - if ((project.end_date - Date.today).to_i) <= 0
                  %dd.money__limit-days 終了
                - else
                  %dd.money__limit-days #{(project.end_date - Date.today).to_i}日
  .ditail
    = link_to "more >", list_projects_path, class: "ditail__botton"

/ 最近始まったプロジェクト
.new
  .new__title 
    = image_tag("new.gif", class: "new__title-image", size: "32x32")
    .new__title-name 最近始まったプロジェクト
  - @new_projects.each do |project|
    .new__area
      = link_to "/projects/#{project.id}", class: "new__area__top" do
        = image_tag("#{project.main_image}", class: "new__area__image", size: "230x129")
        %h2.new__area-text #{project.main_title}
  .ditail
    = link_to "more >", "https://www.makuake.com", class: "ditail__botton"

app/views/projects/new.html.haml
= render partial: "header"
.post__view
  .post
    %h1.post__title プロジェクト投稿
    %p.post__copy 世の中にまだない、新しくて面白い新製品や新サービスを誕生させましょう。
  .post__form
    = form_for (@project), url: planner_projects_path do |f|
      .post__form__project
        .post__form__project-border
        %p.post__copy まず、下記に企画内容を入力しましょう。
        %p.post__copy 全項目入力必須です。魅力たっぷりのあなたの企画をアピールしましょう。
        .post__form__project-border
      .newproject__post__area
        .post__field
          .post__field__text 企画タイトル
          = f.text_field :main_title, class: 'post__field__box form-short', placeholder: '例）50文字以内', maxlength: "50"
        - if @project.errors.full_messages_for(:main_title).any?
          .post__error メインタイトルを入力してください。
        .post__field
          .post__field__text 目標金額
          = f.text_field :goal_price, class: 'post__field__box form-short', placeholder: '例）210000', maxlength: "7"
        - if @project.errors.full_messages_for(:goal_price).any?
          .post__error 目標金額を入力してください。
        .post__field
          .post__field__text 期日
          = f.text_field :end_date, class: 'post__field__box form-short', placeholder: '例）2017-03-22'
        - if @project.errors.full_messages_for(:end_date).any?
          .post__error 期日を入力してください。
        .post__field
          .post__field__text メインイメージ
          .input-file
            = f.file_field :main_image, class: "input-file" do
              %span 選択されていません
        - if @project.errors.full_messages_for(:main_image).any?
          .post__error__image メインイメージを選択してください。
        = f.fields_for :introductions do |i|
          .post__field
            - if request.fullpath == "/planners/1/projects/new"
              = i.hidden_field :intro_index, value: "1"
              .post__field__text.data__title.data__total{data: {title: "#{i.index}", total: "1"}} タイトル
            - else
              = i.hidden_field :intro_index, value: "#{i.object.intro_index}"
              .post__field__text.data__title.data__total{data: {title: "#{i.index}", total: "#{i.object.intro_index}"}} タイトル
            = i.text_field :title, class: 'post__field__box form-short', placeholder: '例）18文字以内', maxlength: "18"
        = f.fields_for :introduction_bodies do |i|
          .post__field
            - if request.fullpath == "/planners/1/projects/new"
              = i.hidden_field :intro_index, value: "2"
              .post__field__text.data__body.data__total{data: {body: "#{i.index}", total: "2"}} テキスト
            - else
              = i.hidden_field :intro_index, value: "#{i.object.intro_index}"
              .post__field__text.data__body.data__total{data: {body: "#{i.index}", total: "#{i.object.intro_index}"}} テキスト
            = i.text_area :body, class: 'post__field__box form-long'
        = f.fields_for :introduction_images do |i|
          .post__field
            - if request.fullpath == "/planners/1/projects/new"
              = i.hidden_field :intro_index, value: "3"
              .post__field__text.data__image.data__total{data: {image: "#{i.index}", total: "3"}} イメージ
            - else
              = i.hidden_field :intro_index, value: "#{i.object.intro_index}"
              .post__field__text.data__image.data__total{data: {image: "#{i.index}", total: "#{i.object.intro_index}"}} イメージ
            .input-file
              = i.file_field :image, class: "input-file" do
                %span 選択されていません
      .btn__area__newproject
        .title__btn__area
          %i.title__plus#title__plus{class: "fa fa-plus-square-o", style:"font-size:22px"}
            .title__plus-text タイトルを追加する
          %i.title__minus#title__minus{class: "fa fa-minus-square-o", style:"font-size:22px"}
            .title__minus-text タイトルを削除する
        .body__btn__area
          %i.body__plus#body__plus{class: "fa fa-file-text-o", style:"font-size:22px"}
            .body__plus-text テキストを追加する
          %i.body__minus#body__minus{class: "fa fa-file-text-o", style:"font-size:22px"}
            .body__minus-text テキストを削除する
        .image__btn__area
          %i.image__plus#image__plus{class: "fa fa-file-image-o", style:"font-size:22px"}
            .image__plus-text イメージを追加する
          %i.image__minus#image__minus{class: "fa fa-file-image-o", style:"font-size:22px"}
            .image__minus-text イメージを削除する
      .post__form__project
        .post__form__project-border
      .tag__form#tag__form
        .tag__input__area
          .tag__input__area-text タグ
          = text_field_tag 'project[genre_list][]', "", class: 'tag__input__area-box', placeholder: '例）お肉'
        .tag__btn__are
          %i.plus__btn{class: "fa fa-plus-square-o", id: "tag__plus"}
            .plus__text タグを追加する
          %i.minus__btn{class: "fa fa-minus-square-o", id: "tag__minus"}
            .minus__text タグを削除する
      .post__form__project
        .post__form__project-border
        %p.post__copy 次に支援者様へのリターンを入力しましょう。
        %p.post__copy こちらも全項目入力必須です。魅力的なリターンを用意しましょう。
        .post__form__project-border
      = f.fields_for :investments do |i|
        .form__box
          .post__field
            .post__field__text リターンタイトル
            = i.text_field :title, class: 'post__field__box form-short', placeholder: '例）40文字以内', maxlength: "40"
          - if @project.investments[i.index].errors.full_messages_for(:title).any?
            .post__error リターンタイトルを入力してください。
          .post__field
            .post__field__text リターン詳細文
            = i.text_area :body, class: 'post__field__box form-long'
          - if @project.investments[i.index].errors.full_messages_for(:body).any?
            .post__error 詳細文を入力してください。
          .post__field
            .post__field__text 金額
            = i.text_field :price, class: 'post__field__box form-short', placeholder: '例）10000', maxlength: "6"
          - if @project.investments[i.index].errors.full_messages_for(:price).any?
            .post__error 金額を入力してください。
          .post__field
            .post__field__text リターン用画像
            .input-file
              = i.file_field :image, class: "input-file" do
                %span 選択されていません
          - if @project.investments[i.index].errors.full_messages_for(:image).any?
            .post__error__image 画像を選択してください。
          .post__field
            .post__field__text 用意個数
            = i.text_field :stock, class: 'post__field__box form-short', placeholder: '例）20', maxlength: "3"
          - if @project.investments[i.index].errors.full_messages_for(:stock).any?
            .post__error 用意している個数を入力してください。
          .post__field
            .post__field__text 納品予定日
            = i.text_field :delivery_date, class: 'post__field__box form-short', placeholder: '例）2017-12-22', maxlength: "10"
          - if @project.investments[i.index].errors.full_messages_for(:delivery_date).any?
            .post__error 納品予定日を入力してください。
          .post__form__project#border__under{data: {number: "#{i.index}"}}
            .post__form__project-border
      %i.plus__btn{class: "fa fa-plus-square-o", id: "plus__btn"}
        .plus__text リターンを追加する
      %i.minus__btn{class: "fa fa-minus-square-o", id: "minus__btn"}
        .minus__text リターンを削除する
      = f.submit "投稿する", class: "post__btn",id: "project__submit__btn"
= render partial: "footer"

app/views/projects/show.html.haml
= render partial: "header"
.project__main
  .project__header
    .project__header__box
      .project__header__link
        = link_to "TOP  >  ", "/", class: "project__header__link-text"
        = link_to "プロジェクト一覧  >  ", "/", class: "project__header__link-text"
        .project__header__link-text #{@project.main_title}
      .project__menu
        = link_to "プロジェクト", "/", class: "nav-btn"
        = link_to "活動レポート", "/", class: "nav-btn"
        = link_to "応援コメント", "/", class: "nav-btn"
  .project
    = image_tag("#{@project.main_image}", class: "project__main__image")
    .project__main__detail
      %dl
        .st__money
          - if @project.clear_rate.round(0) >= 100
            = image_tag("success2.png", class: "st__money-success")
          %project__main__detail
            = image_tag("yen-white.png", class: "st__money-icon")
            .st__money-title 集まっている金額
          %dd.st__money-num #{@project.sum_price.to_s(:delimited)}円
          .st__money-goal 目標金額 #{(@project.goal_price.to_i).to_s(:delimited)}円
      .money__gage.st__money-gage
        - if @project.clear_rate.round(0) > 100
          .money__gage__in{style: "width:100%" }
            .money__gage__in__percent #{@project.clear_rate.round(0)}%
        - else
          .money__gage__in{style: "width:#{@project.clear_rate.round(0)}%" }
            .money__gage__in__percent #{@project.clear_rate.round(0)}%
      %dl
        %dt
          = image_tag("people-white.png", class: "st__money__supporter-icon")
          .st__money__supporter-name サポーター
        %dd.st__money__supporter-count #{@project.investments.map{|investment|(investment.supporters.count)}.sum}人
      %dl
        %dt
          = image_tag("clock-white.png", class: "st__money__limit-icon")
          .st__money__limit-title 残り
        - if ((@project.end_date - Date.today).to_i) <= 0
          %dd.st__money__limit-days 終了
        - else
          %dd.st__money__limit-days #{(@project.end_date - Date.today).to_i}日
      .st__money-btn#st__money-btn 支援するコースを選択する
    .project__main__name
      .project__main__name-text #{@project.main_title}
      - @project.genre_list.each do |tag|
        .tag__btn ##{tag}
    .project__left
      .project__detail
        - @project_show.each do |project|
          - if project.has_attribute?(:title)
            .project__detail__border
            .project__detail__block #{project.title}
            .project__detail__border
          - elsif project.has_attribute?(:body)
            .project__detail__body #{simple_format(project.body)}
          - else
            = image_tag("#{project.image}", class: "project__detail__image")
      .project__detail__bottom
        .investments__btn#investments__btn 支援するコースを選択する
      / = image_tag("logo1.png", class: "project__detail__bottom-image")
      / .project__detail__logo-text “まだここにない”を手に入れよう
      / .project__detail__bottom-box
      /   = image_tag("main_project.jpg", class: "project__detail__bottom-box-image")
      /   .project__detail__bottom-box-fb-link
      /     %p.detail__fb-link-text 
      /       このプロジェクトが気に入ったら
      /       %br
      /         %span.detail__fb-link-text-span いいね!
      /         をしよう
    .project__right
      .investments__bar#investments__bar
        .investments__bar__title 支援するコースを選択する
        .investments__bar__text このプロジェクトは目標金額の達成有無にかかわらず、サポーターがプロジェクトに支援を申し込んだ時点でプロジェクトの成立（売買契約の成立）となります。
        - @project.investments.each do |investment|
          .investments__bar__menu
            .investments__bar__menu-money
              #{investment.price.to_s(:delimited)}円コース
              %span.investments__bar__menu-tax (税込)
            .investments__bar__menu-qty 残り#{(investment.stock.to_i) - (investment.supporters.ids.count)}個
          .investments__bar__detail
            .investments__bar__detail-title #{investment.title}
            = image_tag("#{investment.image}", class: "investments__bar__detail-image")
            .investments__bar__detail-body #{simple_format(investment.body)}
            .investments__supporter-count 
              = image_tag("black-people.png", class: "investments__supporter-count-image")
              .investments__supporter-count-text #{investment.supporters.ids.count}人が支援しています。
            .investments__supporter-duedata
              = image_tag("bag.png", class: "investments__supporter-duedata-image")
              .investments__supporter-duedata-text #{investment.delivery_date.strftime("%Y年%m月")}にお届け予定です。
          .investments__bar__link__box
            - if ((investment.stock.to_i) - (investment.supporters.ids.count)) == 0
              .stockout__btn 在庫切れ
            - else
              - if user_signed_in?
                = link_to "このコースに申し込む",project_investment_path(@project, investment), class: "order__btn"
              - else
                %a.order__btn{data: {toggle: "modal", target: "#my-modal-login-investments"}} このコースに申し込む
        .planner__inquiry
          .planner__inquiry-text 実行者へ問合せ
= render partial: "footer"

.modal#my-modal-login-investments
  .modal-dialog
    .login.my-modal-view
      %h2.login__title ログイン
      %a.login__link{data: {toggle: "modal", target: "#my-modal-signup-investments", dismiss:"modal"}} 新規会員登録はこちら  >
      %p.login__copy ＼企画を支援するにはユーザーログインが必要です!／
      = render partial: "devise/shared/login_new"

.modal#my-modal-signup-investments
  .modal-dialog
    .login.my-modal-view
      %h2.login__title ユーザー登録
      %a.login__link{data: {toggle: "modal", target: "#my-modal-login-investments", dismiss:"modal"}} ログインはこちら >
      %p.login__copy ＼約1分で登録でき、Makuakeを楽しめます!／
      = render partial: "devise/shared/signup_new"