config/routes.rb
Rails.application.routes.draw do
  devise_for :planners, controllers: {
    sessions:      'planners/sessions',
    passwords:     'planners/passwords',
    registrations: 'planners/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root "projects#index"

  resources :projects do
    collection do
      get  'list'
      post 'purchase'
    end
  end

  resources :projects, only: [:show,] do
    resources :investments, only: [:show] do
      resources :supporters, only: [:new, :create] do
        collection do
          post 'confirm'
        end
      end
    end
  end
  resources :planners, only: [:index] do
    resources :projects, only: [:new, :create]
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'password'
    end
  end

  resources :planners, only: [:index, :show, :edit, :update] do
    member do
      get 'password'
      get 'introduction'
    end
  end
end

app/models/planner.rb
class Planner < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
### Association
  has_many :investments
  has_many :projects
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

end

app/controllers/planners/confirmations_controller.rb
class Planners::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/planners/omniauth_callbacks_controller.rb
class Planners::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/planners/passwords_controller.rb
class Planners::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/planners/registrations_controller.rb
class Planners::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
   def update
      self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
      prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
      if resource.update_without_current_password(account_update_params)
        yield resource if block_given?
        if is_flashing_format?
          flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
            :update_needs_confirmation : :updated
          set_flash_message :notice, flash_key
        end
        sign_in resource_name, resource, :bypass => true
        respond_with resource, :location => after_update_path_for(resource)
      else
        clean_up_passwords resource
        respond_with resource
      end
    end


  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/planners/sessions_controller.rb
class Planners::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    if (session[:previous_url] == root_path)
      super
    else
      session[:previous_url] || root_path
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/planners/unlocks_controller.rb
class Planners::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/planners_controller.rb
class PlannersController < ApplicationController
  before_action :set_planner, only: [:update, :edit, :password]

  def introduction
    @planner = Project.find(params[:id]).planner
    @project = @planner.projects.order(created_at: :DESC).limit(1)
  end

  def show
  end

  def edit
  end

  def password
  end

  def update
    if @planner.update(planner_params)
      sign_in(@planner, bypass: true)
      redirect_to root_path, notice:"企画者プロフィールが編集されました。"
    else
      flash.now[:alert] = "プロフィール編集が失敗しました。"
      render :edit
    end
  end

  private
  def planner_params
    params.require(:planner).permit(:name, :image, :email, :location, :birthday, :password, :password_confirmation, :introduction)
  end

  def set_planner
    @planner = Planner.find(params[:id])
    @hold_planner = Planner.find(params[:id])
  end
end

app/helpers/planners_helper.rb
module PlannersHelper
end

app/views/planners/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/planners/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/planners/shared/_login_new.html.haml
.login__sns
  %h3.login__subtitle SNSで登録
  .login__sns__bar
    = link_to "Facebook", "/", class: "login__sns__bar-btn facebook"
  .login__sns__bar
    = link_to "Twitter", "/", class: "login__sns__bar-btn twitter"
  .login__sns__bar
    = link_to "LINE", "/", class: "login__sns__bar-btn line"
  .login__sns__bar
    = link_to "Ameba", "/", class: "login__sns__bar-btn ameba"
.login__makuake
  %h3.login__subtitle Makuake IDでログイン
  = form_for(@planner, url: planner_session_path) do |f|
    .field
      .login__form__text メールアドレス
      = f.email_field :email, class: 'login__form__box'
    .field
      .login__form__text.login__form__margin
        パスワード
        %p.login__form__small
          ※半角英数字
          %br
            6文字以上
      = f.password_field :password, class: 'login__form__box'
    = link_to "パスワードを忘れた方はこちら  >", new_password_path(resource_name), class: "pw__forget"
    .action
      = f.submit "OK", class: 'action-btn-signup'

app/views/planners/shared/_signup_new.html.haml
.login__sns
  %h3.login__subtitle SNSで登録
  .login__sns__bar
    = link_to "Facebook", "/", class: "login__sns__bar-btn facebook"
  .login__sns__bar
    = link_to "Twitter", "/", class: "login__sns__bar-btn twitter"
  .login__sns__bar
    = link_to "LINE", "/", class: "login__sns__bar-btn line"
  .login__sns__bar
    = link_to "Ameba", "/", class: "login__sns__bar-btn ameba"
.login__makuake
  %h3.login__subtitle メールアドレスで新規登録
  = form_for(@planner, url: planner_registration_path) do |f|
    = devise_error_messages!
    .field
      = f.label :メールアドレス, class: "login__form__text"
      = f.email_field :email, class: 'login__form__box'
    .field
      = f.label :name, class: "login__form__text login__form__margin" do
        企画者名
        %p.login__form__small
          ※全角・半角
          %br
            英数字3-20文字
      = f.text_field :name, class: 'login__form__box'
    .field
      = f.label :パスワード, class: "login__form__text login__form__margin" do
        パスワード
        %p.login__form__small
          ※半角英数字
          %br
            6文字以上
      = f.password_field :password, class: 'login__form__box'
    .field
      = f.label :確認, class: "login__form__text"
      = f.password_field :password_confirmation, class: 'login__form__box'
    - if devise_mapping.rememberable?
      .field.login__form__checkbox
        %label
          = f.check_box :remember_me
          = f.label :Makuakeからの最新情報を受取る
      .field.login__form__checkbox
        %label
          = f.check_box :remember_me
          = f.label :利用規約に同意する
    .action
      = f.submit "OK", class: 'action-btn'