config/routes.rb
Rails.application.routes.draw do
  devise_for :planners, controllers: {
    sessions:      'planners/sessions',
    passwords:     'planners/passwords',
    registrations: 'planners/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root "projects#index"

  resources :projects do
    collection do
      get  'list'
      post 'purchase'
    end
  end

  resources :projects, only: [:show,] do
    resources :investments, only: [:show] do
      resources :supporters, only: [:new, :create] do
        collection do
          post 'confirm'
        end
      end
    end
  end
  resources :planners, only: [:index] do
    resources :projects, only: [:new, :create]
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'password'
    end
  end

  resources :planners, only: [:index, :show, :edit, :update] do
    member do
      get 'password'
      get 'introduction'
    end
  end
end

app/models/supporter.rb
class Supporter < ActiveRecord::Base
  belongs_to :investment
  belongs_to :user

  validates :name, presence: true
  validates :gender, presence: true
  validates :birthday, presence: true ,        length: { maximum: 10 }
  validates :mobile, presence: true,          length: { maximum: 11 }
  validates :postal_code, presence: true,    length: { maximum: 7}
  validates :region, presence: true
  validates :city, presence: true
  validates :block, presence: true
  validates :building, presence: true
end

app/controllers/supporters_controller.rb
class SupportersController < ApplicationController
  before_action :set_investment, only: [:new, :create, :confirm]

  def new
    @supporter = @investment.supporters.new
  end

  def create
    @supporter  = current_user.supporters.new(supporter_params)
    if params[:back]
      render :new
    elsif @supporter.save
      Payjp.api_key = PAYJP_SECRET_KEY
      Payjp::Charge.create(currency: 'jpy', amount: 1000, card: params['payjp-token'])
      redirect_to root_path , notice: "ご支援ありがとうございました。"
    else
      flash.now[:alert] = "支援できませんでした。"
      render :new
    end
  end

  def confirm
    @supporter  = current_user.supporters.new(supporter_params)
    if @supporter.invalid?
      flash.now[:alert] = "未入力項目があります。"
      render :new
    end
  end

  private
  def supporter_params
    params.require(:supporter).permit(:name, :gender, :birthday, :mobile, :postal_code, :region, :city, :block, :building).merge(investment_id: params[:investment_id])
  end

  def set_investment
    @investment = Investment.find(params[:investment_id])
  end
end

app/helpers/supporters_helper.rb
module SupportersHelper
end

app/views/supporters/confirm.html.haml
.header
  .inbox
    = link_to "/" do
      = image_tag("makuake-logo.png", class: "inbox__logo")
.main
  .main__investment
    %ul.investment__header
      %li.investment__header-list  1.支払方法の選択
      %li.investment__header-list 2.お届け先の入力
      %li.investment__header-list.list-select 3.申込み内容の確認
      %li.investment__header-list.list-last 4.完了
    .investment__menu
      %h2.investment__menu__title 申し込み内容を確認する

    = form_for (@supporter), url: project_investment_supporters_path do |f|
      .investment__detail
        .post__form
          .confirmation
            .confirmation__dl
              .confirmation__dt 支援金額
              .confirmation__dd #{@supporter.investment.price.to_s(:delimited)}円(税込)
            .confirmation__dl
              .confirmation__dt コース内容
              .confirmation__dd #{simple_format(@supporter.investment.body)}
            .confirmation__dl
              .confirmation__dt お名前
              .confirmation__dd #{@supporter.name}
              = f.hidden_field :name
            .confirmation__dl
              .confirmation__dt 性別
              .confirmation__dd #{@supporter.gender}
              = f.hidden_field :gender
            .confirmation__dl
              .confirmation__dt 誕生日
              .confirmation__dd #{@supporter.birthday}
              = f.hidden_field :birthday
            .confirmation__dl
              .confirmation__dt 電話番号
              .confirmation__dd  #{@supporter.mobile}
              = f.hidden_field :mobile
            .confirmation__dl
              .confirmation__dt お届け先
              .confirmation__dd
                〒#{@supporter.postal_code}
                %br
                  #{@supporter.region}#{@supporter.city}#{@supporter.block}#{" "}#{@supporter.building}
              = f.hidden_field :postal_code
              = f.hidden_field :region
              = f.hidden_field :city
              = f.hidden_field :block
              = f.hidden_field :building
            .confirmation__dl
              .confirmation__dt.last__border 支払い方法
              .confirmation__dd.last__border
                = image_tag("convenience.gif", class: "pay__image-convenience", style: "width:478px")
      .btn__field
        = f.submit "戻る", name: 'back', class: "back__btn"
        / = f.submit "支援する", class: "support__submit next__btn", id: "support__submit"
        %script.payjp-button{"data-key" => "#{PAYJP_PUBLIC_KEY}", :src => "https://checkout.pay.jp", :type => "text/javascript", "data-number" => "ddd"}
    .caution__box
      %p ご確認お願いします
      %p このプロジェクトは目標金額の達成有無にかかわらず、サポーターがプロジェクトに支援を申し込んだ時点でプロジェクトの成立（売買契約の成立）となります。※Makuakeは、プロジェクトオーナーのプロジェクトが必ず成功することや、プロジェクトの品質、リターン内容を保証するものではありません。従って、プロジェクト進行中に関するトラブル、返金要求、リターン返品要求はプロジェクトオーナーの責任のもと行われます。
      %p セキュリティについて
      .caution__inbox
        = image_tag("siteSealImage.gif", class: "caution__inbox-image")
        %p.caution__inbox-text サイトはSSL暗号化通信に対応しておりますので、入力した情報は安全に送信されます。

app/views/supporters/new.html.haml
.header
  .inbox
    = link_to "/" do
      = image_tag("makuake-logo.png", class: "inbox__logo")
.main
  .main__investment
    %ul.investment__header
      %li.investment__header-list  1.支払方法の選択
      %li.investment__header-list.list-select 2.お届け先の入力
      %li.investment__header-list 3.申込み内容の確認
      %li.investment__header-list.list-last 4.完了
    .investment__menu
      %h2.investment__menu__title お届け先情報をご入力ください
      .investment__menu__text
        Makuakeサイトで取得した情報の取り扱いに関する
        = link_to "プライバシーポリシー", "", class: "investment__menu__text-link"
        について

    = form_for (@supporter), url: confirm_project_investment_supporters_path do |f|
      .investment__detail
        .post__form
          .post__field
            .post__field__text 名前
            = f.text_field :name, class: 'post__field__box form-short', placeholder: '例）若松大輔'
          - if @supporter.errors.full_messages_for(:name).any?
            .post__error 名前を入力してください。
          .post__field
            .post__field__text 性別
            .radio__field
              %label
                男
                = f.radio_button :gender, "男"
              %label
                女
                = f.radio_button :gender, "女"
          - if @supporter.errors.full_messages_for(:gender).any?
            .post__error 性別を選択してください。
          .post__field
            .post__field__text 誕生日
            = f.text_field :birthday, class: 'post__field__box form-short', placeholder: '例）1986-12-22', maxlength: "10"
          - if @supporter.errors.full_messages_for(:birthday).any?
            .post__error 誕生日を入力してください。
          .post__field
            .post__field__text 電話番号
            = f.text_field :mobile, class: 'post__field__box form-short', placeholder: '例）09012345678', maxlength: "11"
          - if @supporter.errors.full_messages_for(:mobile).any?
            .post__error 電話番号を入力してください。
          .post__field
            .post__field__text 郵便番号
            = f.text_field :postal_code, class: 'post__field__box form-short', placeholder: '例）3350005', maxlength: "7"
          - if @supporter.errors.full_messages_for(:postal_code).any?
            .post__error 郵便番号を入力してください。
          .post__field
            .post__field__text 都道府県
            = f.text_field :region, class: 'post__field__box form-short', placeholder: '例）埼玉県'
          - if @supporter.errors.full_messages_for(:region).any?
            .post__error 都道府県を入力してください。
          .post__field
            .post__field__text 市町村
            = f.text_field :city, class: 'post__field__box form-short', placeholder: '例）豊田市深見町'
          - if @supporter.errors.full_messages_for(:city).any?
            .post__error 市町村を入力してください。
          .post__field
            .post__field__text 番地
            = f.text_field :block, class: 'post__field__box form-short', placeholder: '例）1287-49'
          - if @supporter.errors.full_messages_for(:block).any?
            .post__error 番地を入力してください。
          .post__field
            .post__field__text 建物名
            = f.text_field :building, class: 'post__field__box form-short', placeholder: '例）メゾン305号室'
          - if @supporter.errors.full_messages_for(:building).any?
            .post__error 建物名を入力してください。
      .btn__field
        = link_to "戻る", project_investment_path(@investment.project_id, @investment), class: "back__btn"
        = f.submit "確認する", class: "support__submit next__btn", id: "support__submit"
    .caution__box
      %p ご確認お願いします
      %p このプロジェクトは目標金額の達成有無にかかわらず、サポーターがプロジェクトに支援を申し込んだ時点でプロジェクトの成立（売買契約の成立）となります。※Makuakeは、プロジェクトオーナーのプロジェクトが必ず成功することや、プロジェクトの品質、リターン内容を保証するものではありません。従って、プロジェクト進行中に関するトラブル、返金要求、リターン返品要求はプロジェクトオーナーの責任のもと行われます。
      %p セキュリティについて
      .caution__inbox
        = image_tag("siteSealImage.gif", class: "caution__inbox-image")
        %p.caution__inbox-text サイトはSSL暗号化通信に対応しておりますので、入力した情報は安全に送信されます。